import majasLocation from "@/app/majas";
import { worldMap } from "@/app/worldMap";
import { locationActions } from "@/app/locationActions";
import omeLocation from "@/app/ome";
import dusLocation from "@/app/dus";
import fenixxLocation from "@/app/fenixx";
import zurkburgerLocation from "@/app/zurkburger";
import deputoLocation from "@/app/deputo";
import bavarianLocation from "@/app/bavarian";
import garazasLocation from "@/app/garazas";
import srotsLocation from "@/app/srots";
import latgaleLocation from "@/app/latgale";
import aplisLocation from "@/app/aplis";
import krustojumsLocation from "@/app/krustojums";
import celsLocation from "@/app/cels";

aplisLocation({ map: worldMap, locationActions });
celsLocation({ map: worldMap, locationActions });
krustojumsLocation({ map: worldMap, locationActions });
majasLocation({ map: worldMap, locationActions });
dusLocation({ map: worldMap, locationActions });
fenixxLocation({ map: worldMap, locationActions });
omeLocation({ map: worldMap, locationActions });
zurkburgerLocation({ map: worldMap, locationActions });
deputoLocation({ map: worldMap, locationActions });
garazasLocation({ map: worldMap, locationActions });
bavarianLocation({ map: worldMap, locationActions });
srotsLocation({ map: worldMap, locationActions });
latgaleLocation({ map: worldMap, locationActions });
